### ISSUE TITLE
Defining the Web App

### ISSUE THREAD

**Issue by rachelhisko** [rachelchrisjeremy/web-app#3]
- [x] Empathy Map
- [x] Problem Statement
- [x]  App Definition Statement

**Comment by jeremyahkupo** [comment]
### Problem Statement
Young professionals **need a way to** find networking events and opportunities **because** building connections with industry professionals can create jobs opportunities.

**Comment by jeremyahkupo** [comment]
### App Definition Statement
_App Name_ **is a** networking app **that enables** young professionals **to** build professional connections.
