### ISSUE TITLE
Sprint 5/6 review

### ISSUE THREAD

**Issue by rachelhisko** [rachelchrisjeremy/web-app#46]
Review what you did

**Comment by rachelhisko** [comment]
I think sprint 5 & 6 went well. We completed our tasks and have come far along with our coding. 
Sprint 5 &  week I was tasked with sketching out the large screen wireframes so that we had a better understanding of what it will look like larger. I was also tasked with coding all the section that are involved in our website.

**Comment by rachelhisko** [comment]
@thomasjbradley

**Comment by jeremyahkupo** [comment]
We came into week 7 with a lot more code than we anticipated. We coded many different sections and we are going to continue doing that this coming week, along with linking each file together. I was tasked with completing some of the navigation and basic layouts of the profile and event screens.

**Comment by thomasjbradley** [comment]
Amazing work on the Sprint reviews, Issues & Project boards—keep it up!

- But, don’t forget to close Projects & Issues after the Sprint has completed.
