### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by rachelhisko** [rachelchrisjeremy/web-app#61]

**Comment by jeremyahkupo** [comment]
This week, I added all the images across the entire website, like profile images for people and events, along with smaller images for the list of people attending and the event cards.

**Comment by rachelhisko** [comment]
This week I was tasked to put everything together. I placed everything together and tried to make things link to each other. I also edited some layout issues and changed some naming. Team Peta finished everything that needed to be done for this week.

**Comment by rachelhisko** [comment]
@thomasjbradley

**Comment by chris-hough** [comment]
I worked on coding the nav, in different colour versions for all screen sizes. Hit some snags and will have to redo some parts.
